version: "3.2"

services:
  accounts-api:
    image: accounts-api
    build:
      context: AccountsApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=2cl9i
      - AWS_SECRET_ACCESS_KEY=vymxp
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  accounts-api-test:
    image: accounts-api-test
    build:
      context: .
      dockerfile: AccountsApi.Tests/Dockerfile
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=2cl9i
      - AWS_SECRET_ACCESS_KEY=vymxp
    links:
      - dynamodb-database

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000